// apps/angular-demo/src/app/app.component.ts
import { Component, signal, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule } from   '@angular/forms';

// Types (from bizz-components) 
type ButtonVariant = 'primary' | 'secondary' | 'danger' | 'disabled';
type ButtonSize    = 'sm' | 'md' | 'lg';
type TagColor      = 'primary' | 'secondary' | 'success' | 'warning' | 'error';

/**
 * CUSTOM_ELEMENTS_SCHEMA tells Angular's compiler to allow unknown
 * element names (our web components) in templates without errors.
 */
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  // Cross-app navigation
  readonly isLocal = location.hostname === 'localhost' || location.hostname === '127.0.0.1';
  readonly vanillaUrl = this.isLocal ? 'http://localhost:4200' : '../';
  readonly reactUrl   = this.isLocal ? 'http://localhost:4201' : '../react/';

  isDark = signal(false);

  toggleTheme() {
    this.isDark.update(v => !v);
    document.body.classList.toggle('bizz-theme-dark');
    document.body.classList.toggle('dark-page');
  }

  readonly tokens = signal([
    { prop: '--bizz-primary',   label: 'Primary',   color: '#0f62fe' },
    { prop: '--bizz-secondary', label: 'Secondary', color: '#525252' },
    { prop: '--bizz-success',   label: 'Success',   color: '#24a148' },
    { prop: '--bizz-warning',   label: 'Warning',   color: '#f59e0b' },
    { prop: '--bizz-error',     label: 'Error',     color: '#da1e28' },
  ]);

  readonly defaultTokens = this.tokens().map(t => ({ ...t }));

  updateToken(prop: string, color: string) {
    document.documentElement.style.setProperty(prop, color);
    this.tokens.update(tokens =>
      tokens.map(t => (t.prop === prop ? { ...t, color } : t))
    );
  }

  resetTokens() {
    this.defaultTokens.forEach(({ prop, color }) => {
      document.documentElement.style.setProperty(prop, color);
    });
    this.tokens.set(this.defaultTokens.map(t => ({ ...t })));
  }

  // Button demo 
  buttonVariant = signal<ButtonVariant>('primary');
  buttonSize    = signal<ButtonSize>('md');
  buttonLabel   = signal('Click me');
  buttonDisabled = signal(false);
  buttonLoading  = signal(false);
  buttonFullWidth = signal(false);
  buttonLastEvent = signal<string | null>(null);

  readonly buttonVariants: ButtonVariant[] = ['primary', 'secondary', 'danger', 'disabled'];
  readonly buttonSizes: ButtonSize[]       = ['sm', 'md', 'lg'];

  /**
   * Angular binds to custom events with standard (eventName)="handler()" syntax.
   * For bizz-click, it's (bizz-click)="onBizzClick($event)".
   *
   * The $event is a CustomEvent, cast it for typed access to .detail.
   */
  onBizzClick(event: Event) {
    const e = event as CustomEvent;
    this.buttonLastEvent.set(`bizz-click fired at ${new Date().toLocaleTimeString()}`);
    console.log('bizz-click detail:', e.detail);
  }

  // Tag demo
  tagColor       = signal<TagColor>('primary');
  tagLabel       = signal('TypeScript');
  tagDismissible = signal(false);
  tagDismissed   = signal(false);

  readonly tagColors: TagColor[] = ['primary', 'secondary', 'success', 'warning', 'error'];

  onTagDismissed() {
    this.tagDismissed.set(true);
  }

  restoreTag() {
    this.tagDismissed.set(false);
  }

  // Input demo 
  inputValue    = signal('');
  inputError    = signal('');
  inputDisabled = signal(false);
  inputRequired = signal(false);

  onBizzInput(event: Event) {
    this.inputValue.set((event as CustomEvent<string>).detail);
    this.inputError.set('');
  }

  onBizzBlur() {
    if (this.inputRequired() && !this.inputValue()) {
      this.inputError.set('This field is required');
    }
  }

  // Card demo
  cardElevation = signal<'flat' | 'raised'>('raised');
  cardPadding   = signal<'none' | 'sm' | 'md' | 'lg'>('md');
  cardClickable = signal(false);
}

<!-- Header -->
<header class="header">
  <div class="header-brand">
    <span class="logo">bizz-components</span>
    <span class="badge">Angular demo</span>
    <span class="badge secondary">v0.2.0</span>
  </div>
  <div class="header-actions">
    <a [href]="vanillaUrl" class="stack-link" target="_blank">Vanilla ↗</a>
    <a [href]="reactUrl"   class="stack-link" target="_blank">React ↗</a>
    <button class="theme-btn" (click)="toggleTheme()">
      {{ isDark() ? '☀️ ' : '🌙' }}
    </button>
  </div>
</header>

<div class="token-bar">
  <span class="token-bar-label">Theme/color tokens</span>
  <div class="swatches">
    @for (token of tokens(); track token.prop) {
      <div class="swatch">
        <div class="swatch-box" [style.background]="token.color">
          <input
            type="color"
            [value]="token.color"
            (input)="updateToken(token.prop, $any($event.target).value)"
            [title]="'Edit ' + token.prop"
          />
        </div>
        <span class="swatch-label">{{ token.label }}</span>
      </div>
    }
  </div>
  <button class="reset-btn" (click)="resetTokens()">Reset</button>
</div>

<main class="main">
  <div class="intro">
    <h1 class="page-title">Integration</h1>
    <p class="page-desc">
      Web components work in Angular with <strong>CUSTOM_ELEMENTS_SCHEMA</strong> on the
      component/module. Attribute binding uses <strong>[attr]="value"</strong> and custom
      events use lit standard <strong>(bizz-click)="handler($event)"</strong> syntax.
    </p>
  </div>

  <section class="demo-section" id="button">
    <div class="demo-header">
      <h2 class="demo-title">
        Button <code>&lt;bizz-button&gt;</code>
      </h2>
      <p class="demo-desc">
        Angular binds to custom events with standard <code>(bizz-click)="handler($event)"</code>.
        Boolean attributes use Angular's <code>[attr.disabled]="value || null"</code> pattern
        to omit the attribute entirely when false.
      </p>
    </div>

    <div class="demo-card">
      <div class="demo-preview">
        <bizz-button
          [attr.variant]="buttonVariant()"
          [attr.size]="buttonSize()"
          [attr.disabled]="buttonDisabled() || null"
          [attr.loading]="buttonLoading() || null"
          [attr.full-width]="buttonFullWidth() || null"
          (bizz-click)="onBizzClick($event)">
          {{ buttonLabel() }}
        </bizz-button>

        @if (buttonLastEvent()) {
          <span class="event-badge">{{ buttonLastEvent() }}</span>
        }
      </div>

      <div class="demo-controls">
        <label class="ctrl-group">
          <span>Variant</span>
          <select [value]="buttonVariant()" (change)="buttonVariant.set($any($event.target).value)">
            @for (v of buttonVariants; track v) {
              <option [value]="v">{{ v }}</option>
            }
          </select>
        </label>

        <label class="ctrl-group">
          <span>Size</span>
          <select [value]="buttonSize()" (change)="buttonSize.set($any($event.target).value)">
            @for (s of buttonSizes; track s) {
              <option [value]="s">{{ s }}</option>
            }
          </select>
        </label>

        <label class="ctrl-group">
          <span>Label</span>
          <input type="text" [value]="buttonLabel()" (input)="buttonLabel.set($any($event.target).value)" />
        </label>

        <div class="ctrl-group ctrl-toggles">
          <label>
            <input type="checkbox" [checked]="buttonDisabled()" (change)="buttonDisabled.set($any($event.target).checked)" />
            Disabled
          </label>
          <label>
            <input type="checkbox" [checked]="buttonLoading()" (change)="buttonLoading.set($any($event.target).checked)" />
            Loading
          </label>
          <label>
            <input type="checkbox" [checked]="buttonFullWidth()" (change)="buttonFullWidth.set($any($event.target).checked)" />
            Full width
          </label>
        </div>
      </div>
    </div>
  </section>

  <section class="demo-section" id="tag">
    <div class="demo-header">
      <h2 class="demo-title">Tag <code>&lt;bizz-tag&gt;</code></h2>
      <p class="demo-desc">
        Handle it with <code>(bizz-dismissed)="handler()"</code>.
      </p>
    </div>

    <div class="demo-card">
      <div class="demo-preview">
        @if (tagDismissed()) {
          <div class="dismissed-msg">
            Tag dismissed!
            <button (click)="restoreTag()">Restore</button>
          </div>
        } @else {
          <bizz-tag
            [attr.color]="tagColor()"
            [attr.dismissible]="tagDismissible() || null"
            (bizz-dismissed)="onTagDismissed()"
          >
            {{ tagLabel() }}
          </bizz-tag>
        }
      </div>

      <div class="demo-controls">
        <label class="ctrl-group">
          <span>Color</span>
          <select [value]="tagColor()" (change)="tagColor.set($any($event.target).value)">
            @for (c of tagColors; track c) {
              <option [value]="c">{{ c }}</option>
            }
          </select>
        </label>
        <label class="ctrl-group">
          <span>Label</span>
          <input type="text" [value]="tagLabel()" (input)="tagLabel.set($any($event.target).value)" />
        </label>
        <div class="ctrl-group ctrl-toggles">
          <label>
            <input type="checkbox" [checked]="tagDismissible()" (change)="tagDismissible.set($any($event.target).checked)" />
            Dismissible
          </label>
        </div>
      </div>

      <div class="demo-all-variants">
        <p class="variants-label">All colors</p>
        <div class="variants-row">
          @for (c of tagColors; track c) {
            <bizz-tag [attr.color]="c">{{ c }}</bizz-tag>
          }
        </div>
      </div>
    </div>
  </section>

  <section class="demo-section" id="input">
    <div class="demo-header">
      <h2 class="demo-title">Input <code>&lt;bizz-input&gt;</code></h2>
      <p class="demo-desc">
        Listen to <code>bizz-input</code> for value changes and <code>bizz-blur</code>
        for blur events. Access the value via <code>($event as CustomEvent).detail</code>.
      </p>
    </div>

    <div class="demo-card">
      <div class="demo-preview">
        <bizz-input
          label="Email address"
          placeholder="you@example.com"
          type="email"
          helper-text="We'll never share your email."
          [attr.error-text]="inputError() || null"
          [attr.disabled]="inputDisabled() || null"
          [attr.required]="inputRequired() || null"
          (bizz-input)="onBizzInput($event)"
          (bizz-blur)="onBizzBlur()"
          style="width: 320px; max-width: 100%"
        ></bizz-input>

        @if (inputValue()) {
          <p class="event-badge">Current value: {{ inputValue() }}</p>
        }
      </div>

      <div class="demo-controls">
        <div class="ctrl-group ctrl-toggles">
          <label>
            <input type="checkbox" [checked]="inputDisabled()" (change)="inputDisabled.set($any($event.target).checked)" />
            Disabled
          </label>
          <label>
            <input type="checkbox" [checked]="inputRequired()" (change)="inputRequired.set($any($event.target).checked)" />
            Required
          </label>
        </div>
      </div>
    </div>
  </section>

  <section class="demo-section" id="card">
    <div class="demo-header">
      <h2 class="demo-title">Card <code>&lt;bizz-card&gt;</code></h2>
      <p class="demo-desc">
        Named slots are declared in HTML as <code>slot="card-header"</code>. Angular's template
        syntax works the same as plain HTML here.
      </p>
    </div>

    <div class="demo-card">
      <div class="demo-preview">
        <bizz-card
          [attr.elevation]="cardElevation()"
          [attr.padding]="cardPadding()"
          [attr.clickable]="cardClickable() || null"
          style="width: 280px; max-width: 100%"
        >
          <div slot="card-header">
            <p class="bizz-label" style="color: var(--bizz-text-secondary); margin-bottom: 0.25rem">Design System</p>
            <h4 class="bizz-h4">bizz-components</h4>
          </div>
          <p class="bizz-body-sm" style="color: var(--bizz-text-secondary)">
            Framework-agnostic web component library built with Lit.
          </p>
          <div slot="card-footer" style="display: flex; gap: 0.5rem; flex-wrap: wrap">
            <bizz-tag color="primary" size="sm">Lit</bizz-tag>
            <bizz-tag color="secondary" size="sm">TypeScript</bizz-tag>
            <bizz-tag color="success" size="sm">Published</bizz-tag>
          </div>
        </bizz-card>
      </div>

      <div class="demo-controls">
        <label class="ctrl-group">
          <span>Elevation</span>
          <select [value]="cardElevation()" (change)="cardElevation.set($any($event.target).value)">
            <option value="flat">flat</option>
            <option value="raised">raised</option>
          </select>
        </label>
        <label class="ctrl-group">
          <span>Padding</span>
          <select [value]="cardPadding()" (change)="cardPadding.set($any($event.target).value)">
            <option value="none">none</option>
            <option value="sm">sm</option>
            <option value="md">md</option>
            <option value="lg">lg</option>
          </select>
        </label>
        <div class="ctrl-group ctrl-toggles">
          <label>
            <input type="checkbox" [checked]="cardClickable()" (change)="cardClickable.set($any($event.target).checked)" />
            Clickable
          </label>
        </div>
      </div>
    </div>
  </section>
</main>

// apps/react-demo/src/App.tsx
import { useState, useRef, useCallback } from 'react';
import './app.css';

const isLocal = () => location.hostname === 'localhost' || location.hostname === '127.0.0.1';

type ButtonVariant = 'primary' | 'secondary' | 'danger' | 'disabled';
type ButtonSize    = 'sm' | 'md' | 'lg';
type TagColor      = 'primary' | 'secondary' | 'success' | 'warning' | 'error';

const DEFAULT_TOKENS: Record<string, string> = {
  '--bizz-primary':   '#0f62fe',
  '--bizz-secondary': '#525252',
  '--bizz-success':   '#24a148',
  '--bizz-warning':   '#f59e0b',
  '--bizz-error':     '#da1e28',
};

const TOKEN_LABELS: Record<string, string> = {
  '--bizz-primary':   'Primary',
  '--bizz-secondary': 'Secondary',
  '--bizz-success':   'Success',
  '--bizz-warning':   'Warning',
  '--bizz-error':     'Error',
};

function TokenSwatch({ prop, label }: { prop: string; label: string }) {
  const [color, setColor] = useState(DEFAULT_TOKENS[prop]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setColor(val);
    document.documentElement.style.setProperty(prop, val);
  };

  return (
    <div className="swatch">
      <div className="swatch-box" style={{ background: color }}>
        <input type="color" value={color} onChange={handleChange} title={`Edit ${prop}`} />
      </div>
      <span className="swatch-label">{label}</span>
    </div>
  );
}

function ButtonDemo() {
  const [variant, setVariant]     = useState<ButtonVariant>('primary');
  const [size, setSize]           = useState<ButtonSize>('md');
  const [label, setLabel]         = useState('Click me');
  const [disabled, setDisabled]   = useState(false);
  const [loading, setLoading]     = useState(false);
  const [fullWidth, setFullWidth] = useState(false);
  const [lastEvent, setLastEvent] = useState<string | null>(null);

  // Web component custom events need a ref + addEventListener
  // (React's synthetic events don't cover custom event names like bizz-click)
  const btnRef = useRef<HTMLElement>(null);

  const handleBizzClick = useCallback(() => {
    setLastEvent(`bizz-click fired at ${new Date().toLocaleTimeString()}`);
  }, []);

  const setRef = useCallback(
    (el: HTMLElement | null) => {
      (btnRef as React.MutableRefObject<HTMLElement | null>).current = el;
      if (el) {
        el.addEventListener('bizz-click', handleBizzClick);
      }
    },
    [handleBizzClick]
  );

  return (
    <section className="demo-section" id="button">
      <div className="demo-header">
        <h2 className="demo-title">Button <code>&lt;bizz-button&gt;</code></h2>
        <p className="demo-desc">
          Custom events like <code>bizz-click</code> need a <strong>ref + addEventListener</strong>.
          React's synthetic event system doesn't cover non-standard event names
        </p>
      </div>

      <div className="demo-card">
        <div className="demo-preview">

          <bizz-button
            ref={setRef}
            variant={variant}
            size={size}
            disabled={disabled || undefined}
            loading={loading || undefined}
            full-width={fullWidth || undefined}
          >
            {label}
          </bizz-button>
          {lastEvent && <span className="event-badge">{lastEvent}</span>}
        </div>

        <div className="demo-controls">
          <label className="ctrl-group">
            <span>Variant</span>
            <select value={variant} onChange={e => setVariant(e.target.value as ButtonVariant)}>
              {(['primary','secondary','danger','disabled'] as ButtonVariant[]).map(v => (
                <option key={v}>{v}</option>
              ))}
            </select>
          </label>

          <label className="ctrl-group">
            <span>Size</span>
            <select value={size} onChange={e => setSize(e.target.value as ButtonSize)}>
              {(['sm','md','lg'] as ButtonSize[]).map(s => <option key={s}>{s}</option>)}
            </select>
          </label>

          <label className="ctrl-group">
            <span>Label</span>
            <input type="text" value={label} onChange={e => setLabel(e.target.value)} />
          </label>

          <div className="ctrl-group ctrl-toggles">
            <label><input type="checkbox" checked={disabled} onChange={e => setDisabled(e.target.checked)} /> Disabled</label>
            <label><input type="checkbox" checked={loading} onChange={e => setLoading(e.target.checked)} /> Loading</label>
            <label><input type="checkbox" checked={fullWidth} onChange={e => setFullWidth(e.target.checked)} /> Full width</label>
          </div>
        </div>
      </div>
    </section>
  );
}

function TagDemo() {
  const [color, setColor]           = useState<TagColor>('primary');
  const [label, setLabel]           = useState('TypeScript');
  const [dismissible, setDismissible] = useState(false);
  const [dismissed, setDismissed]   = useState(false);

  const setRef = useCallback((el: HTMLElement | null) => {
    if (el) {
      el.addEventListener('bizz-dismissed', () => setDismissed(true));
    }
  }, []);

  return (
    <section className="demo-section" id="tag">
      <div className="demo-header">
        <h2 className="demo-title">Tag <code>bizz-tag</code></h2>
      </div>

      <div className="demo-card">
        <div className="demo-preview">
          {dismissed ? (
            <div className="dismissed-msg">
              Tag dismissed! <button onClick={() => setDismissed(false)}>Restore</button>
            </div>
          ) : (
            <bizz-tag ref={setRef} color={color} dismissible={dismissible || undefined}>
              {label}
            </bizz-tag>
          )}
        </div>

        <div className="demo-controls">
          <label className="ctrl-group">
            <span>Color</span>
            <select value={color} onChange={e => setColor(e.target.value as TagColor)}>
              {(['primary','secondary','success','warning','error'] as TagColor[]).map(c => (
                <option key={c}>{c}</option>
              ))}
            </select>
          </label>
          <label className="ctrl-group">
            <span>Label</span>
            <input type="text" value={label} onChange={e => setLabel(e.target.value)} />
          </label>
          <div className="ctrl-group ctrl-toggles">
            <label><input type="checkbox" checked={dismissible} onChange={e => setDismissible(e.target.checked)} /> Dismissible</label>
          </div>
        </div>

        <div className="demo-all-variants">
          <p className="variants-label">All colors</p>
          <div className="variants-row">
            {(['primary','secondary','success','warning','error'] as TagColor[]).map(c => (
              <bizz-tag key={c} color={c}>{c}</bizz-tag>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Input demo ───────────────────────────────────────────────────────────────
function InputDemo() {
  const [value, setValue]       = useState('');
  const [error, setError]       = useState('');
  const [disabled, setDisabled] = useState(false);
  const [required, setRequired] = useState(false);

  const setRef = useCallback((el: HTMLElement | null) => {
    if (el) {
      el.addEventListener('bizz-input', (e: Event) => {
        setValue((e as CustomEvent<string>).detail);
        setError('');
      });
      el.addEventListener('bizz-blur', () => {
        if (required && !value) setError('This field is required');
      });
    }
  }, [required, value]);

  return (
    <section className="demo-section" id="input">
      <div className="demo-header">
        <h2 className="demo-title">Input <code>&lt;bizz-input&gt;</code></h2>
        <p className="demo-desc">
          <code>bizz-input</code> fires a <code>CustomEvent string</code> cast the event
          to access <code>e.detail</code>. Connect via ref for full TypeScript safety.
        </p>
      </div>

      <div className="demo-card">
        <div className="demo-preview">
          <bizz-input
            ref={setRef}
            label="Email address"
            placeholder="you@example.com"
            type="email"
            helper-text="We'll never share your email."
            error-text={error}
            disabled={disabled || undefined}
            required={required || undefined}
            style={{ width: '320px', maxWidth: '100%' }}
          />
          {value && <p className="event-badge">Current value: {value}</p>}
        </div>

        <div className="demo-controls">
          <div className="ctrl-group ctrl-toggles">
            <label><input type="checkbox" checked={disabled} onChange={e => setDisabled(e.target.checked)} /> Disabled</label>
            <label><input type="checkbox" checked={required} onChange={e => setRequired(e.target.checked)} /> Required</label>
          </div>
        </div>
      </div>
    </section>
  );
}

export default function App() {
  const [dark, setDark] = useState(false);

  const toggleTheme = () => {
    setDark(d => !d);
    document.body.classList.toggle('bizz-theme-dark');
    document.body.classList.toggle('dark-page');
  };

  const resetTokens = () => {
    Object.entries(DEFAULT_TOKENS).forEach(([prop, val]) => {
      document.documentElement.style.setProperty(prop, val);
    });
    window.dispatchEvent(new Event('tokens-reset'));
  };

  return (
    <div className="app">
      {/* Header */}
      <header className="header">
        <div className="header-brand">
          <span className="logo">bizz-components</span>
          <span className="badge">React demo</span>
          <span className="badge secondary">v0.3.0</span>
        </div>
        <div className="header-actions">
          <a href={isLocal() ? 'http://localhost:4200' : '../'} className="stack-link" target="_blank">Vanilla ↗</a>
          <a href={isLocal() ? 'http://localhost:4202' : '../angular/'} className="stack-link" target="_blank">Angular ↗</a>
          <button className="theme-btn" onClick={toggleTheme}>
            {dark ? '☀️ Light' : '🌙 Dark'}
          </button>
        </div>
      </header>

      {/* Token bar */}
      <div className="token-bar">
        <span className="token-bar-label">Theme tokens</span>
        <div className="swatches">
          {Object.entries(DEFAULT_TOKENS).map(([prop]) => (
            <TokenSwatch key={prop} prop={prop} label={TOKEN_LABELS[prop]} />
          ))}
        </div>
        <button className="reset-btn" onClick={resetTokens}>Reset</button>
      </div>

      {/* Content */}
      <main className="main">
        <div className="intro">
          <h1 className="page-title">React integration</h1>
          <p className="page-desc">
            bizz-components are native Custom Elements: they work in React like any HTML element.
            Key patterns: register once at entry, use <strong>refs for custom events</strong>,
            pass <strong>undefined (not false) for absent boolean attributes</strong>.
          </p>
        </div>

        <ButtonDemo />
        <TagDemo />
        <InputDemo />
      </main>
    </div>
  );
}
